# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/danilo/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/201.7223.86/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/danilo/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/201.7223.86/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/danilo/Documents/own/c++/ncurses_dice

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/danilo/Documents/own/c++/ncurses_dice

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/danilo/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/201.7223.86/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/danilo/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/201.7223.86/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/danilo/Documents/own/c++/ncurses_dice/CMakeFiles /home/danilo/Documents/own/c++/ncurses_dice/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/danilo/Documents/own/c++/ncurses_dice/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dice

# Build rule for target.
dice: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dice
.PHONY : dice

# fast build rule for target.
dice/fast:
	$(MAKE) -f CMakeFiles/dice.dir/build.make CMakeFiles/dice.dir/build
.PHONY : dice/fast

src/controller/DiceController.o: src/controller/DiceController.cpp.o

.PHONY : src/controller/DiceController.o

# target to build an object file
src/controller/DiceController.cpp.o:
	$(MAKE) -f CMakeFiles/dice.dir/build.make CMakeFiles/dice.dir/src/controller/DiceController.cpp.o
.PHONY : src/controller/DiceController.cpp.o

src/controller/DiceController.i: src/controller/DiceController.cpp.i

.PHONY : src/controller/DiceController.i

# target to preprocess a source file
src/controller/DiceController.cpp.i:
	$(MAKE) -f CMakeFiles/dice.dir/build.make CMakeFiles/dice.dir/src/controller/DiceController.cpp.i
.PHONY : src/controller/DiceController.cpp.i

src/controller/DiceController.s: src/controller/DiceController.cpp.s

.PHONY : src/controller/DiceController.s

# target to generate assembly for a file
src/controller/DiceController.cpp.s:
	$(MAKE) -f CMakeFiles/dice.dir/build.make CMakeFiles/dice.dir/src/controller/DiceController.cpp.s
.PHONY : src/controller/DiceController.cpp.s

src/model/DiceModel.o: src/model/DiceModel.cpp.o

.PHONY : src/model/DiceModel.o

# target to build an object file
src/model/DiceModel.cpp.o:
	$(MAKE) -f CMakeFiles/dice.dir/build.make CMakeFiles/dice.dir/src/model/DiceModel.cpp.o
.PHONY : src/model/DiceModel.cpp.o

src/model/DiceModel.i: src/model/DiceModel.cpp.i

.PHONY : src/model/DiceModel.i

# target to preprocess a source file
src/model/DiceModel.cpp.i:
	$(MAKE) -f CMakeFiles/dice.dir/build.make CMakeFiles/dice.dir/src/model/DiceModel.cpp.i
.PHONY : src/model/DiceModel.cpp.i

src/model/DiceModel.s: src/model/DiceModel.cpp.s

.PHONY : src/model/DiceModel.s

# target to generate assembly for a file
src/model/DiceModel.cpp.s:
	$(MAKE) -f CMakeFiles/dice.dir/build.make CMakeFiles/dice.dir/src/model/DiceModel.cpp.s
.PHONY : src/model/DiceModel.cpp.s

src/view/DiceView.o: src/view/DiceView.cpp.o

.PHONY : src/view/DiceView.o

# target to build an object file
src/view/DiceView.cpp.o:
	$(MAKE) -f CMakeFiles/dice.dir/build.make CMakeFiles/dice.dir/src/view/DiceView.cpp.o
.PHONY : src/view/DiceView.cpp.o

src/view/DiceView.i: src/view/DiceView.cpp.i

.PHONY : src/view/DiceView.i

# target to preprocess a source file
src/view/DiceView.cpp.i:
	$(MAKE) -f CMakeFiles/dice.dir/build.make CMakeFiles/dice.dir/src/view/DiceView.cpp.i
.PHONY : src/view/DiceView.cpp.i

src/view/DiceView.s: src/view/DiceView.cpp.s

.PHONY : src/view/DiceView.s

# target to generate assembly for a file
src/view/DiceView.cpp.s:
	$(MAKE) -f CMakeFiles/dice.dir/build.make CMakeFiles/dice.dir/src/view/DiceView.cpp.s
.PHONY : src/view/DiceView.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... dice"
	@echo "... src/controller/DiceController.o"
	@echo "... src/controller/DiceController.i"
	@echo "... src/controller/DiceController.s"
	@echo "... src/model/DiceModel.o"
	@echo "... src/model/DiceModel.i"
	@echo "... src/model/DiceModel.s"
	@echo "... src/view/DiceView.o"
	@echo "... src/view/DiceView.i"
	@echo "... src/view/DiceView.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

